### ISSUE TITLE
Hibernate/Mysql exception logged evey hour.

### ISSUE THREAD

**Issue by matthewlenz** [Athou/commafeed#1007]
Site appears to work just fine but I don't know if this is expected or not.  Here are the log entries:

```
ERROR [2022-07-24 14:47:51,606] org.hibernate.engine.jdbc.spi.SqlExceptionHelper: HOUR_OF_DAY: 2 -> 3
ERROR [2022-07-24 14:47:51,607] com.commafeed.backend.task.ScheduledTask: org.hibernate.exception.GenericJDBCException: could not execute query
! java.lang.IllegalArgumentException: HOUR_OF_DAY: 2 -> 3
! at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:2829)
! at java.util.Calendar.updateTime(Calendar.java:3393)
! at java.util.Calendar.getTimeInMillis(Calendar.java:1782)
! at com.mysql.cj.result.SqlTimestampValueFactory.localCreateFromDatetime(SqlTimestampValueFactory.java:191)
! ... 51 common frames omitted
! Causing: com.mysql.cj.exceptions.WrongArgumentException: HOUR_OF_DAY: 2 -> 3
! at sun.reflect.GeneratedConstructorAccessor125.newInstance(Unknown Source)
! at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
! at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
! at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
! at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
! at com.mysql.cj.result.SqlTimestampValueFactory.localCreateFromDatetime(SqlTimestampValueFactory.java:195)
! at com.mysql.cj.result.SqlTimestampValueFactory.localCreateFromDatetime(SqlTimestampValueFactory.java:51)
! at com.mysql.cj.result.AbstractDateTimeValueFactory.createFromDatetime(AbstractDateTimeValueFactory.java:104)
! at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeDatetime(MysqlTextValueDecoder.java:90)
! at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:86)
! at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:243)
! at com.mysql.cj.protocol.a.result.ByteArrayRow.getValue(ByteArrayRow.java:91)
! ... 45 common frames omitted
! Causing: java.sql.SQLException: HOUR_OF_DAY: 2 -> 3
! at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
! at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
! at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
! at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
! at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
! at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:85)
! at com.mysql.cj.jdbc.result.ResultSetImpl.getTimestamp(ResultSetImpl.java:947)
! at com.mysql.cj.jdbc.result.ResultSetImpl.getTimestamp(ResultSetImpl.java:985)
! at org.hibernate.type.descriptor.sql.TimestampTypeDescriptor$2.doExtract(TimestampTypeDescriptor.java:84)
! at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)
! at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257)
! at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253)
! at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:243)
! at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:329)
! at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:3214)
! at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1887)
! at org.hibernate.loader.Loader.hydrateEntityState(Loader.java:1811)
! at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1784)
! at org.hibernate.loader.Loader.getRow(Loader.java:1624)
! at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:748)
! at org.hibernate.loader.Loader.getRowsFromResultSet(Loader.java:1047)
! at org.hibernate.loader.Loader.processResultSet(Loader.java:998)
! at org.hibernate.loader.Loader.doQuery(Loader.java:967)
! at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
! at org.hibernate.loader.Loader.doList(Loader.java:2868)
! ... 26 common frames omitted
! Causing: org.hibernate.exception.GenericJDBCException: could not execute query
! at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
! at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
! at org.hibernate.loader.Loader.doList(Loader.java:2871)
! at org.hibernate.loader.Loader.doList(Loader.java:2850)
! at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
! at org.hibernate.loader.Loader.list(Loader.java:2677)
! at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540)
! at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
! at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
! at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1459)
! at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649)
! at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
! ... 17 common frames omitted
! Causing: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute query
! at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
! at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1626)
! at org.hibernate.query.Query.getResultList(Query.java:165)
! at com.querydsl.jpa.impl.AbstractJPAQuery.getResultList(AbstractJPAQuery.java:160)
! at com.querydsl.jpa.impl.AbstractJPAQuery.fetch(AbstractJPAQuery.java:202)
! at com.commafeed.backend.dao.FeedEntryDAO.deleteOldEntries(FeedEntryDAO.java:57)
! at com.commafeed.backend.service.DatabaseCleaningService.lambda$cleanEntriesForFeedsExceedingCapacity$5(DatabaseCleaningService.java:89)
! at com.commafeed.backend.dao.UnitOfWork.call(UnitOfWork.java:27)
! at com.commafeed.backend.service.DatabaseCleaningService.cleanEntriesForFeedsExceedingCapacity(DatabaseCleaningService.java:88)
! at com.commafeed.backend.task.OldEntriesCleanupTask.run(OldEntriesCleanupTask.java:24)
! at com.commafeed.backend.task.ScheduledTask$1.run(ScheduledTask.java:23)
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
! at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
! at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66)
! at java.lang.Thread.run(Thread.java:745)
```

**Comment by Athou** [comment]
It's probably one of the cleanup tasks that fails since it happens at fixed times.

After googling a little bit, it seems to be linked to this bug report: https://bugs.mysql.com/bug.php?id=82005

I don't know if it's a bug or a feature but we have two choices:
- you could try to add "default_time_zone = UTC" to your my.cnf as mentionned in the link
- I could revert the mysql driver to the 5.x version since this issue seems to only happen with versions 6+ of the driver

What do you think?

**Comment by matthewlenz** [comment]
No I think keeping up-to-date with the newest mysql driver is the way to go.  I'm currently passing TZ=America/Chicago into the container.  If I remove it it'll use UTC.  I think that last commenter is saying that the setting needs to be explicit though. If I pass in TZ=... to commafeed will it show me dates/time on the entries using that timezone?  If not I'm just going to bail on using mysql with commafeed.  I'll export my feeds and switch to just using the default (h2).

**Comment by matthewlenz** [comment]
@Athou didn't want to create a new bug just to ask a question about switching to H2.  Is there is anything special I need to do to initialize the db?  The only thing I did was switch the dsn from:

`url: jdbc:h2:/home/commafeed/db;mv_store=false`

to

`url: jdbc:h2:/commafeed/db;mv_store=false`

Because I run it using docker:

```
docker run -d \
    --name commafeed \
    --expose 8082 \
    -e TZ=America/Chicago \
    -u 1000:1000 \
    -v $HOME/containers/commafeed:/commafeed \
    -w /commafeed \
    java:latest \
        java -Djava.net.preferIPv4Stack=true -jar commafeed.jar server config.yml
```

It doesn't seem to like that though and I'm getting:

`ERROR [2022-07-25 14:34:41,445] org.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool.`

The directory I'm bind mounting only has the config, jar, log directory, and sessions directory (the last two being created by commafeed).

**Comment by Athou** [comment]
> No I think keeping up-to-date with the newest mysql driver is the way to go. 

I agree :)

> I'm currently passing TZ=America/Chicago into the container (mysql container). If I remove it it'll use UTC. I think that last commenter is saying that the setting needs to be explicit though. If I pass in TZ=... to commafeed will it show me dates/time on the entries using that timezone? If not I'm just going to bail on using mysql with commafeed. I'll export my feeds and switch to just using the default (h2).

I think what is needed is to configure MySQL to treat dates as in UTC. I don't know if setting the TZ env variable is changing the behavior of MySQL.
CommaFeed is storing dates as timestamps so it would make sense to configure MySQL with the UTC timezone.



> url: jdbc:h2:/commafeed/db;mv_store=false

Could you try without `;mv_store=false`? I think it was to work around an issue with an older version of h2 and is not needed anymore. If it works I will update the example configuration.

FWIW I'm running commafeed.com with PostgreSQL, but h2 should work just fine.

**Comment by matthewlenz** [comment]
removing the ;mv_store=false did in fact fix the issue if you'd like to remove it from the sample permanently.

**Comment by Athou** [comment]
Thanks!

**Comment by matthewlenz** [comment]
I did find one other new issue with H2.  The mark read Items older than xx no longer works.  The regular mark as read works fine though.

**Comment by Athou** [comment]
Looks like I used the date the entry was inserted in the database as the date to determine if an entry is before or after the threshold while the date displayed is the date the entry was updated.
No entries are marked as read in your case since all your entries were inserted today.

I just pushed a fix for this : https://github.com/Athou/commafeed/commit/152f0bd727e6d683f7cb333fb845fc14caac3a25
