### ISSUE TITLE
liquibase.lockservice: Waiting for changelog lock....

### ISSUE THREAD

**Issue by maxpowerstl** [Athou/commafeed#1020]
Any idea how to resolve this issue?  Just started happening yesterday.  It never makes it past this step.

**Comment by Athou** [comment]
It could happen if CommaFeed crashed or was killed during the small window at startup when liquibase locks the database to apply potential changes.

Executing this query should solve the issue: 

    UPDATE DATABASECHANGELOGLOCK SET LOCKED=0

**Comment by matthewlenz** [comment]
(responding on my other github account).  Thanks.  Forgive my ignorance. I've never used liquibase is there a command line utility? and if so is there a way to execute this using the commafeed.jar?

**Comment by Athou** [comment]
There was not but there is now in the latest jar built from develop here https://github.com/Athou/commafeed/actions/runs/3469284416

I thought you might need it :)

You can then run `java -jar commafeed.jar db locks --force-release config.yml`

If you don't want to migrate to CommaFeed 3.0 you can just put this jar next to the other one with another name and it should work.

**Comment by matthewlenz** [comment]
Gave it a try but no luck.  Here is the output:

```
$ java -jar commafeed3.jar db locks --force-release config.yml
WARN  [2022-11-15 10:32:45,135] org.hibernate.validator.internal.properties.javabean.JavaBeanExecutable: HV000254: Missing parameter metadata for CacheType(String, int), which declares implicit or synthetic parameters. Automatic resolution of generic type information for method parameters may yield incorrect results if multiple parameters have the same erasure. To solve this, compile your code with the '-parameters' flag.
org.h2.message.DbException: Log file error: "/commafeed/db.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/commafeed"" [90062-214]" [90034-214]
org.h2.message.DbException: Log file error: "/commafeed/db.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/commafeed"" [90062-214]" [90034-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.TraceSystem.logWritingError(TraceSystem.java:294)
	at org.h2.message.TraceSystem.openWriter(TraceSystem.java:315)
	at org.h2.message.TraceSystem.writeFile(TraceSystem.java:263)
	at org.h2.message.TraceSystem.write(TraceSystem.java:247)
	at org.h2.message.Trace.error(Trace.java:187)
	at org.h2.engine.Database.<init>(Database.java:395)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:347)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:228)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:769)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:697)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:496)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:121)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:110)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:134)
	at io.dropwizard.migrations.AbstractLiquibaseCommand.createDatabase(AbstractLiquibaseCommand.java:94)
	at io.dropwizard.migrations.AbstractLiquibaseCommand.openLiquibase(AbstractLiquibaseCommand.java:79)
	at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:67)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:191)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Log file error: "/commafeed/db.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/commafeed"" [90062-214]" [90034-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 29 more
Caused by: org.h2.message.DbException: Error while creating file "/commafeed" [90062-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.store.fs.disk.FilePathDisk.createDirectory(FilePathDisk.java:356)
	at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:85)
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:382)
	at org.h2.message.TraceSystem.openWriter(TraceSystem.java:305)
	... 26 more
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error while creating file "/commafeed" [90062-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 31 more
Caused by: java.nio.file.AccessDeniedException: /commafeed
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at org.h2.store.fs.disk.FilePathDisk.createDirectory(FilePathDisk.java:347)
	... 29 more
org.h2.jdbc.JdbcSQLNonTransientException: Error while creating file "/commafeed" [90062-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.store.fs.disk.FilePathDisk.createDirectory(FilePathDisk.java:356)
	at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:85)
	at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:382)
	at org.h2.mvstore.db.Store.<init>(Store.java:109)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
ERROR [2022-11-15 16:32:47,969] org.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool.
! java.nio.file.AccessDeniedException: /commafeed
! at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
! at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
! at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
! at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
! at java.base/java.nio.file.Files.createDirectory(Files.java:700)
! at org.h2.store.fs.disk.FilePathDisk.createDirectory(FilePathDisk.java:347)
! ... 26 common frames omitted
! Causing: org.h2.jdbc.JdbcSQLNonTransientException: Error while creating file "/commafeed" [90062-214]
! at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
! at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
! at org.h2.message.DbException.get(DbException.java:212)
! at org.h2.store.fs.disk.FilePathDisk.createDirectory(FilePathDisk.java:356)
! at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:85)
! at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:382)
! at org.h2.mvstore.db.Store.<init>(Store.java:109)
! at org.h2.engine.Database.<init>(Database.java:324)
! at org.h2.engine.Engine.openSession(Engine.java:92)
! at org.h2.engine.Engine.openSession(Engine.java:222)
! at org.h2.engine.Engine.createSession(Engine.java:201)
! at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
! at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
! at org.h2.Driver.connect(Driver.java:59)
! at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:347)
! at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:228)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:769)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:697)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:496)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:121)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:110)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:134)
! at io.dropwizard.migrations.AbstractLiquibaseCommand.createDatabase(AbstractLiquibaseCommand.java:94)
! at io.dropwizard.migrations.AbstractLiquibaseCommand.openLiquibase(AbstractLiquibaseCommand.java:79)
! at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:67)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:191)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:347)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:228)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:769)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:697)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:496)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:121)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:110)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:134)
	at io.dropwizard.migrations.AbstractLiquibaseCommand.createDatabase(AbstractLiquibaseCommand.java:94)
	at io.dropwizard.migrations.AbstractLiquibaseCommand.openLiquibase(AbstractLiquibaseCommand.java:79)
	at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:67)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:191)
Caused by: java.nio.file.AccessDeniedException: /commafeed
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at org.h2.store.fs.disk.FilePathDisk.createDirectory(FilePathDisk.java:347)
	... 26 more
```

**Comment by matthewlenz** [comment]
I ended up restoring from a backup and it appears to be working well.  Not really sure what happened.

**Comment by Athou** [comment]
Not sure, looks like you don't have permission to access the h2 db file (`/commafeed/db.trace.db"`). Is commafeed running with another user usually?

**Comment by matthewlenz** [comment]
Nope. Same user.  I think it might have just been corrupted or something.  This is what backups are for :D  I don't really add new feeds often so nothing was lost.

**Comment by matthewlenz** [comment]
Scratch that.  Good call.  I that config path was set-up for running inside a bind mount.
