### ISSUE TITLE
Add option to configure path to "sessions"

### ISSUE THREAD

**Issue by Jorengarenar** [Athou/commafeed#1028]
It seems `sessions` are created in current working directory. It would be nice to be able to point to more appropriate location in config file.

**Comment by Athou** [comment]
I think you should be able to configure that with `session.path` in your `config.yml`.

**Comment by Jorengarenar** [comment]
I've added the following to the config:
```yml
session:
  path: ${XDG_SHARE_HOME}/commafeed/sessions
```

But I'm getting an error:
```
io.dropwizard.configuration.ConfigurationParsingException: config.yml has an error:
  * Unrecognized field at: session.path

        at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:277)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:141)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:90)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:139)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:197)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "path" (class com.commafeed.frontend.session.SessionHandlerFactory), not marked as ignorable (0 known properties: ]) at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: com.commafeed.CommaFeedConfiguration["session"]->com.commafeed.frontend.session.SessionHandlerFactory["path"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:277)
        at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4650)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:128
        ... 6 more
```

Line "`Unrecognized field "path" (class com.commafeed.frontend.session.SessionHandlerFactory), not marked as ignorable (0 known properties: ]`" caught my attention

**Comment by Athou** [comment]
Yep you're right I reproduced the error. I just pushed a fix for this on `develop`.

Could you please try again with the jar that was generated here https://github.com/Athou/commafeed/actions/runs/3837204726 ?
You may also pull `develop` and rebuild locally.

**Comment by Jorengarenar** [comment]
Great, now it works  :+1:
