### ISSUE TITLE
Cannot run Commafeed

### ISSUE THREAD

**Issue by TroySigX** [Athou/commafeed#1048]
Java version: openjdk 17.0.6 2023-01-17
Trying to run the command: `java -Djava.net.preferIPv4Stack=true -jar target/commafeed.jar server config.yml` gives the following error:
``` 
WARN  [2023-03-27 05:15:02,143] org.hibernate.validator.internal.properties.javabean.JavaBeanExecutable: HV000254: Missing parameter metadata for CacheType(String, int), which declares implicit or synthetic parameters. Automatic resolution of generic type information for method parameters may yield incorrect results if multiple parameters have the same erasure. To solve this, compile your code with the '-parameters' flag.
org.h2.message.DbException: Log file error: "/home/commafeed/db.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/home/commafeed"" [90062-214]" [90034-214]
ERROR [2023-03-27 05:15:05,947] org.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool.
! java.nio.file.AccessDeniedException: /home/commafeed
! at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
! at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
! at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
! at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
! at java.base/java.nio.file.Files.createDirectory(Files.java:700)
! at org.h2.store.fs.disk.FilePathDisk.createDirectory(FilePathDisk.java:347)
! ... 47 common frames omitted
! Causing: org.h2.jdbc.JdbcSQLNonTransientException: Error while creating file "/home/commafeed" [90062-214]
! at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
! at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
! at org.h2.message.DbException.get(DbException.java:212)
! at org.h2.store.fs.disk.FilePathDisk.createDirectory(FilePathDisk.java:356)
! at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:85)
! at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:382)
! at org.h2.mvstore.db.Store.<init>(Store.java:109)
! at org.h2.engine.Database.<init>(Database.java:324)
! at org.h2.engine.Engine.openSession(Engine.java:92)
! at org.h2.engine.Engine.openSession(Engine.java:222)
! at org.h2.engine.Engine.createSession(Engine.java:201)
! at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
! at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
! at org.h2.Driver.connect(Driver.java:59)
! at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:347)
! at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:228)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:769)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:697)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:496)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:121)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:110)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:134)
! at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
! at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)
! at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
! at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
! at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
! at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:175)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
! at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:173)
! at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)
! at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
! at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
! at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
! at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:709)
! at io.dropwizard.hibernate.SessionFactoryFactory.buildSessionFactory(SessionFactoryFactory.java:102)
! at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:51)
! at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:41)
! at io.dropwizard.hibernate.HibernateBundle.run(HibernateBundle.java:73)
! at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:66)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:180)
WARN  [2023-03-27 05:15:05,949] org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: HHH000342: Could not obtain connection to query metadata
! java.nio.file.AccessDeniedException: /home/commafeed
! at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
! at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
! at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
! at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
! at java.base/java.nio.file.Files.createDirectory(Files.java:700)
! at org.h2.store.fs.disk.FilePathDisk.createDirectory(FilePathDisk.java:347)
! ... 47 common frames omitted
! Causing: org.h2.jdbc.JdbcSQLNonTransientException: Error while creating file "/home/commafeed" [90062-214]
! at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
! at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
! at org.h2.message.DbException.get(DbException.java:212)
! at org.h2.store.fs.disk.FilePathDisk.createDirectory(FilePathDisk.java:356)
! at org.h2.store.fs.FileUtils.createDirectory(FileUtils.java:85)
! at org.h2.store.fs.FileUtils.createDirectories(FileUtils.java:382)
! at org.h2.mvstore.db.Store.<init>(Store.java:109)
! at org.h2.engine.Database.<init>(Database.java:324)
! at org.h2.engine.Engine.openSession(Engine.java:92)
! at org.h2.engine.Engine.openSession(Engine.java:222)
! at org.h2.engine.Engine.createSession(Engine.java:201)
! at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
! at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
! at org.h2.Driver.connect(Driver.java:59)
! at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:347)
! at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:228)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:769)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:697)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:496)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:121)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:110)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:134)
! at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
! at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)
! at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
! at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
! at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
! at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:175)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
! at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:173)
! at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)
! at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
! at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
! at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
! at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:709)
! at io.dropwizard.hibernate.SessionFactoryFactory.buildSessionFactory(SessionFactoryFactory.java:102)
! at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:51)
! at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:41)
! at io.dropwizard.hibernate.HibernateBundle.run(HibernateBundle.java:73)
! at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:66)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:180)
```

**Comment by Athou** [comment]
Looks like the user you're using to run CommaFeed does not have acess to `/home/commafeed` : 

    java.nio.file.AccessDeniedException: /home/commafeed

**Comment by TroySigX** [comment]
Thank you @Athou ! It works.
