### ISSUE TITLE
Error: Unable to create initial connections of pool

### ISSUE THREAD

**Issue by tcfjr** [Athou/commafeed#1165]
**Describe the bug**
Commafeed has been running well for 6+ weeks on my Synology DS220+ under Docker.  This morning, it errored and will not start, with the LOG showing this error:

`org.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool`

**To Reproduce**
Restarting the container does not change the behavior.

**Expected behavior**
No errors and a clean start-up are expected.

**Screenshots**
Here's the log entries for this issue:

> ERROR [2023-11-02 18:06:06,700] org.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool.
! java.net.SocketTimeoutException: Connect timed out
! at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
! at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
! at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
! at java.base/java.net.Socket.connect(Unknown Source)
! at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
! at org.postgresql.core.PGStream.<init>(PGStream.java:98)
! at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
! at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
! ... 41 common frames omitted
! Causing: org.postgresql.util.PSQLException: The connection attempt failed.
! at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
! at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
! at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
! at org.postgresql.Driver.makeConnection(Driver.java:443)
! at org.postgresql.Driver.connect(Driver.java:297)
! at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:346)
! at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:227)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:768)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:696)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:495)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:153)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131)
! at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
! at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)
! at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
! at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
! at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)
! at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:175)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:295)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:252)
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)
! at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:173)
! at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)
! at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
! at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
! at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
! at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:709)
! at io.dropwizard.hibernate.SessionFactoryFactory.buildSessionFactory(SessionFactoryFactory.java:102)
! at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:51)
! at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:41)
! at io.dropwizard.hibernate.HibernateBundle.run(HibernateBundle.java:73)
! at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:66)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:224)
org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:284)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)
	at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:175)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:295)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:252)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:173)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:709)
	at io.dropwizard.hibernate.SessionFactoryFactory.buildSessionFactory(SessionFactoryFactory.java:102)
	at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:51)
	at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:41)
	at io.dropwizard.hibernate.HibernateBundle.run(HibernateBundle.java:73)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:66)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:224)
Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100)
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:138)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272)
      
	... 22 more

**Environment (please complete the following information):**

- CommaFeed version: latest
- Device: Synology DS220+ NAS using Docker

**Additional context**

**Comment by tcfjr** [comment]
After some further investigation, this issue seems to have been caused by a bad firewall updated.  Closing with prejudice.
