### ISSUE TITLE
Need more documentation on HTTPS setup

### ISSUE THREAD

**Issue by ojhunt** [Athou/commafeed#633]
I have what i thought should be a completely valid tomcat keystore at this point but i have yet to convince it to launch.

Anyway, the documentation did not immediately suggest the need for a tomcat store (I'd swear i saw a change go through that dropped tomcat, but maybe i am misremembering one of the db changes).

I'll put up a change to add config.example.yml, but i'm not sure it's sufficient:
 #    - type: https
 #      port: 8453
 #      keyStorePassword: sssshhhItsSecret
 #      keyStorePath: /path/to/my/keys.keystore
 #      certAlias: certAlias

But i'm seeing:
WARN  [2014-09-29 15:44:24,530] org.eclipse.jetty.util.component.AbstractLifeCycle: FAILED SslContextFactory@57f06755(/home/ubuntu/certs/reader.keystore,/home/ubuntu/certs/reader.keystore): java.lang.IllegalStateException: Unable to retrieve certificate chain
! java.lang.IllegalStateException: Unable to retrieve certificate chain
! at org.eclipse.jetty.util.security.CertificateValidator.validate(CertificateValidator.java:179) ~[commafeed.jar:2.0.3-SNAPSHOT]
! at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:293) ~[commafeed.jar:2.0.3-SNAPSHOT]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [commafeed.jar:2.0.3-SNAPSHOT]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) [commafeed.jar:2.0.3-SNAPSHOT]
! at org.eclipse.jetty.server.Server.start(Server.java:342) [commafeed.jar:2.0.3-SNAPSHOT]
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) [commafeed.jar:2.0.3-SNAPSHOT]
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) [commafeed.jar:2.0.3-SNAPSHOT]
! at org.eclipse.jetty.server.Server.doStart(Server.java:290) [commafeed.jar:2.0.3-SNAPSHOT]
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [commafeed.jar:2.0.3-SNAPSHOT]
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) [commafeed.jar:2.0.3-SNAPSHOT]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43) [commafeed.jar:2.0.3-SNAPSHOT]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [commafeed.jar:2.0.3-SNAPSHOT]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [commafeed.jar:2.0.3-SNAPSHOT]
! at io.dropwizard.Application.run(Application.java:72) [commafeed.jar:2.0.3-SNAPSHOT]
! at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:159) [commafeed.jar:2.0.3-SNAPSHOT]

**Comment by ojhunt** [comment]
Yeah it seems that nginx or similar is the correct way of handling this - I just use a simple open shift setup for me alone, I don't understand the actual mechanics or running servers just the maths :)
