### ISSUE TITLE
[Openshift] CommaFeed deploy failed

### ISSUE THREAD

**Issue by icaroperseo** [Athou/commafeed#700]
By following the procedure described in the README, I get the following error:

```
...
remote: [INFO]     at Object.<anonymous> (/var/lib/openshift/54bd1d2b4382ec16060000e5/app-root/runtime/repo/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:181:15)
remote: [INFO]     at Module._compile (module.js:456:26)
remote: [INFO]     at Object.Module._extensions..js (module.js:474:10)
remote: [INFO]     at Module.load (module.js:356:32)
remote: [INFO]     at Function.Module._load (module.js:312:12)
remote: [INFO]     at Module.require (module.js:364:17)
remote: [INFO] npm ERR! weird error 8
remote: [INFO] npm ERR! not ok code 0
remote: [INFO] ------------------------------------------------------------------------
remote: [INFO] BUILD FAILURE
remote: [INFO] ------------------------------------------------------------------------
remote: [INFO] Total time: 12:20.295s
remote: [INFO] Finished at: Mon Jan 19 10:27:49 EST 2015
remote: [INFO] Final Memory: 13M/189M
remote: [INFO] ------------------------------------------------------------------------
remote: [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.20:npm (npm install) on project commafeed: Failed to run task: 'npm install --color=false' failed. (error code 1) -> [Help 1]
remote: [ERROR] 
remote: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
remote: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
remote: [ERROR] 
remote: [ERROR] For more information about the errors and possible solutions, please read the following articles:
remote: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
remote: An error occurred executing 'gear postreceive' (exit code: 1)
remote: Error message: CLIENT_ERROR: Failed to execute action hook 'build' for 54bd1d2b4382ec16060000e5 application commafeed
remote: 
remote: For more details about the problem, try running the command again with the '--trace' option.
```

Is there any way to fix it?

Regards

**Comment by Athou** [comment]
I'll have a look, thanks for the report.

**Comment by Athou** [comment]
I commited some changes it should now build correctly.

**Comment by icaroperseo** [comment]
Sorry but now I get the following error:

```
remote: [INFO] Including org.postgresql:postgresql:jar:9.4-1200-jdbc41 in the shaded jar.
remote: [INFO] Including com.github.dblock.waffle:waffle-jna:jar:1.7 in the shaded jar.
remote: [INFO] Including net.java.dev.jna:jna:jar:4.1.0 in the shaded jar.
remote: [INFO] Including net.java.dev.jna:jna-platform:jar:4.1.0 in the shaded jar.
remote: [INFO] Including net.sourceforge.jtds:jtds:jar:1.3.1 in the shaded jar.
Connection to commafeed-site.rhcloud.com closed by remote host.
fatal: The remote end hung up unexpectedly
error: error in sideband demultiplexer
To ssh://54e4111ce.......db000006@commafeed-site.rhcloud.com/~/git/commafeed.git/
   4cb5585..6d91216  master -> master
error: failed to push some refs to 'ssh://54e4111ce....db000006@commafeed-site.rhcloud.com/~/git/commafeed.git/'
```
