### ISSUE TITLE
openshift build - java version?

### ISSUE THREAD

**Issue by uncomplimentary** [Athou/commafeed#731]
i am trying to build and run the thing on openshift.  everything seems to install correctly, but when i try to start it, this shows up in commafeed.log.  any suggestions?

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/commafeed/CommaFeedApplication : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by Athou** [comment]
what about now ?

**Comment by uncomplimentary** [comment]
.openshift/config.mysql.yml has an error:
  * Malformed YAML at line: 76, column: 9; while scanning for the next token; found character @ '@' that cannot start any token. (Do not use @
 for indentation);  in 'reader', line 76, column 9:
      user: @OPENSHIFT_MYSQL_DB_USERNAME@
            ^

**Comment by Athou** [comment]
It seems that the environment variable OPENSHIFT_MYSQL_DB_USERNAME is not set, which should not happen. Is MySQL installed on your openshift instance?

**Comment by uncomplimentary** [comment]
yes, i followed the instructions (personal information redacted):


$ rhc create-app commafeed diy-0.1 mysql-5.5
Application Options
-------------------
Domain:     ***
Cartridges: diy-0.1, mysql-5.5
Gear Size:  default
Scaling:    no

Creating application 'commafeed' ... done

  Disclaimer: This is an experimental cartridge that provides a way to try unsupported languages, frameworks, and middleware on OpenShift.

MySQL 5.5 database added.  Please make note of these credentials:

       Root User: ***
   Root Password: ***
   Database Name: commafeed

Connection URL: mysql://$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/

You can manage your new MySQL database by also embedding phpmyadmin.
The phpmyadmin username and password will be the same as the MySQL credentials above.
