### ISSUE TITLE
Fresh install ubuntu

### ISSUE THREAD

**Issue by FlatlandNative** [Athou/commafeed#751]
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/commafeed/CommaFeedApplication : Unsupported major.minor version 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

Receiving this error after following the instructions, only thing different is I have openjdk-7-jdk installed. I have a mysql database "commafeed" setup with a user "commafeed" passwd "commafeed", I placed all of that info inside of my config.yml located in the root of the commafeed folder. The only thing I noticed that was weird is I had to manually mount the "target" folder and then wget the .jar file.

I noticed this error is similar to issue #731 with redshift, the only reason I created a separate issue is because I am just attempting an install on a local server, nothing to do with redshift. Let me know if any further information is needed or if you want me to try something. Thanks in advance.

**Comment by Athou** [comment]
CommaFeed requires java 8 since v2.2.0.
If you can't upgrade your jdk version, you can use commafeed v2.1.0

**Comment by FlatlandNative** [comment]
Alright, was kind of figuring that might be the problem. Will attempt to use v2.1.0 then as installing openjdk-8-jdk seems to not be the most stable solution in ubuntu from what I have read. Thanks for the quick response.

**Comment by FlatlandNative** [comment]
is there a jar file for 2.1.0 or any instructions that would help guide me through configuring it without a jar?

**Comment by FlatlandNative** [comment]
Was able to figure out the installation of 2.1.0 using: https://github.com/dsferruzza/david.sferruzza.fr/blob/master/posts/2014-08-18-how-to-install-commafeed-rss-reader.md in case anyone runs into this same problem.
