### ISSUE TITLE
TypeError: LRU: key must be a string or number.

### ISSUE THREAD

**Issue by pjz** [Athou/commafeed#812]
I noticed this while building, and sure enough it's on [Travis](https://travis-ci.org/Athou/commafeed#L2909) too:

```
[ERROR] TypeError: LRU: key must be a string or number. Almost certainly a bug! undefined
[ERROR]     at typeCheckKey (/home/travis/build/Athou/commafeed/node_modules/lru-cache/lib/lru-cache.js:20:19)
[ERROR]     at LRUCache.get (/home/travis/build/Athou/commafeed/node_modules/lru-cache/lib/lru-cache.js:230:3)
[ERROR]     at /home/travis/build/Athou/commafeed/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:122:70
[ERROR]     at _fulfilled (/home/travis/build/Athou/commafeed/node_modules/q/q.js:834:54)
[ERROR]     at self.promiseDispatch.done (/home/travis/build/Athou/commafeed/node_modules/q/q.js:863:30)
[ERROR]     at Promise.promise.promiseDispatch (/home/travis/build/Athou/commafeed/node_modules/q/q.js:796:13)
[ERROR]     at /home/travis/build/Athou/commafeed/node_modules/q/q.js:857:14
[ERROR]     at runSingle (/home/travis/build/Athou/commafeed/node_modules/q/q.js:137:13)
[ERROR]     at flush (/home/travis/build/Athou/commafeed/node_modules/q/q.js:125:13)
[ERROR]     at process._tickCallback (node.js:448:13)

```

**Comment by pjz** [comment]
I'm guessing it must've been quietly fixed sometime in the last 5.5 years.
