### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by floydwilde** [Athou/commafeed#908]
After recently patching Java on an Ubuntu bionic server with this version: 

```
commafeed@neibu:~/commafeed$ java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Ubuntu-3ubuntu118.04.3)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Ubuntu-3ubuntu118.04.3, mixed mode, sharing)
```
 I am getting this error trying to start a commafeed (2.4.0) install which was previously working ok: 

```
commafeed@neibu:~/commafeed$ java -Djava.net.preferIPv4Stack=true -jar commafeed.jar server config.yml
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.hibernate.validator.internal.util.Version.getJavaRelease(Version.java:36)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:120)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:106)
        at org.hibernate.validator.HibernateValidator.createSpecializedConfiguration(HibernateValidator.java:27)
        at org.hibernate.validator.HibernateValidator.createSpecializedConfiguration(HibernateValidator.java:24)
        at javax.validation.Validation$ProviderSpecificBootstrapImpl.configure(Validation.java:220)
        at io.dropwizard.validation.BaseValidator.newConfiguration(BaseValidator.java:28)
        at io.dropwizard.jersey.validation.Validators.newConfiguration(Validators.java:35)
        at io.dropwizard.jersey.validation.Validators.newValidatorFactory(Validators.java:27)
        at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:68)
        at io.dropwizard.Application.run(Application.java:72)
        at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:172)

```

**Comment by floydwilde** [comment]
I cloned the master branch, copied my configuration which I've only changed to use a MySQL database, and now the application starts ok.  There are a few warnings now when I start it up: 

```
commafeed@neibu:~/git/commafeed$ java -Djava.net.preferIPv4Stack=true -jar target/commafeed.jar server config.yml
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.module.afterburner.util.MyClassLoader (file:/opt/commafeed/git/commafeed/target/commafeed.jar) to method java.lang.ClassLoader.defineClass(java.lang.St
ring,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.module.afterburner.util.MyClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
I don't know what they mean, but possibly this issue is resolved.

**Comment by Athou** [comment]
I made changes recently to support java 9+ (https://github.com/Athou/commafeed/issues/904). The app works fine but there are warning like these.
They can be ignored for now. It would be nice if Jackson was updated though. The discussion takes place here https://github.com/FasterXML/jackson-modules-base/issues/37
