### ISSUE TITLE
Can't launch server

### ISSUE THREAD

**Issue by lacer** [Athou/commafeed#917]
Hi,
I've got no idea how Github works, I hope this is the right way to ask a question. I tried to deploy Commafeed by myself, unfortunately it didn't work. I receive the following error message:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.hibernate.validator.internal.util.Version.getJavaRelease(Version.java:36)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:120)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.<init>(ConfigurationImpl.java:106)
        at org.hibernate.validator.HibernateValidator.createSpecializedConfiguration(HibernateValidator.java:27)
        at org.hibernate.validator.HibernateValidator.createSpecializedConfiguration(HibernateValidator.java:24)
        at javax.validation.Validation$ProviderSpecificBootstrapImpl.configure(Validation.java:220)
        at io.dropwizard.validation.BaseValidator.newConfiguration(BaseValidator.java:28)
        at io.dropwizard.jersey.validation.Validators.newConfiguration(Validators.java:35)
        at io.dropwizard.jersey.validation.Validators.newValidatorFactory(Validators.java:27)
        at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:68)
        at io.dropwizard.Application.run(Application.java:72)
        at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:172)

```

I followed the steps from the instructions (download & run, not that hard, I guess). What came to my attention is, that nowhere is written, if Commafeed needs additional libraries / packages. I installed 

- libhibernate3-java 

- libhibernate-validator-java

- libdropwizard-metrics-java

on Debian (Raspbian, if this is relevant, but the message is the same on Arch Linux) but this didn't help, the error message stays the same. The Java packages I installed are 

- openjdk-11-jre-headless

- openjdk-11-jre

- openjdk-11-jdk

Am I missing something obvious here?

Thank you very much for your help!

**Comment by Athou** [comment]
No additional libraries are needed, but the precompiled package only supports java8.
You need to either install java8 or compile CommaFeed yourself.
See https://github.com/Athou/commafeed/issues/908

I'll try to find some time to bump CommaFeed version and compile for java9+ later today.

**Comment by lacer** [comment]
Thank you very much, that did the trick!
One of the best softwares I ever used, keep up the good work :-)
