### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by ScuttleSE** [Athou/commafeed#937]
After having my server running for month I just restarted it, and took the time to get the latest code from git.

Now I get this when I start:
```
ERROR [2020-05-16 07:47:56,842] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
,! liquibase.exception.ValidationFailedException: Validation Failed:
,!      1 change sets check sum
,!           changelogs/db.changelog-1.0.xml::create-users::athou was: 8:ca2d6edef0263a78cab9cc0942972d50 but is now: 8:a19e9e8007137d83c8a6b9ead5a2ecac
,! 
,! at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:276)
,! at liquibase.Liquibase.update(Liquibase.java:198)
,! at liquibase.Liquibase.update(Liquibase.java:179)
,! at liquibase.Liquibase.update(Liquibase.java:175)
,! at liquibase.Liquibase.update(Liquibase.java:168)
,! at com.commafeed.backend.service.StartupService.lambda$updateSchema$2(StartupService.java:67)
,! ... 22 common frames omitted```

**Comment by ScuttleSE** [comment]
After reverting to bb429afd95ae5c5e86599ecb22d0e9c05a8eef5c I got it up and running again, so there is something odd in the latest commit

**Comment by Athou** [comment]
Hi,

Thanks for the report. I commited a change that should fix the issue, although I'm not sure why you have the error to begin with.
I hope you won't get the same error for another changeSet, if you do let me know.

**Comment by dos1** [comment]
I just got
```
ERROR [2020-05-22 02:11:16,375] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! liquibase.exception.ValidationFailedException: Validation Failed:
!      5 change sets check sum
!           changelogs/db.changelog-1.0.xml::create-app-settings::athou was: 8:4453304273ff7f1b095e83240bf176e0 but is now: 8:b92da3e1d6fc0e55ab7056f861fe3a0c
!           changelogs/db.changelog-1.0.xml::create-cat::athou was: 8:316a80e427241a4bf7a3e9db908c2996 but is now: 8:531b6ae85a8026559f9daa7078c3c297
!           changelogs/db.changelog-1.0.xml::create-statuses::athou was: 8:df2678511ba8ad87fee51aa3e1aac26d but is now: 8:44886681f6ea292d11729bcd1fa755fc
!           changelogs/db.changelog-1.0.xml::create-users::athou was: 8:97bcb18a90dbbf89252d9dab38cb719d but is now: 8:4868360a987096a67048845fb6321902
!           changelogs/db.changelog-1.0.xml::create-user-settings::athou was: 8:3528d8cb1988e72c9ed566d224a88d10 but is now: 8:b296201d9301897cbfec8967b807e259
```

on latest master after updating from ea5fccfe5f931fa4483c8fff72c7bb20f9e91825.

**Comment by chkrefr** [comment]
I'm seeing this same issue after trying to upgrade to v2.6.0.  Running Ubuntu 20.04 fully patched and utilizing a MySQL database, everything worked great until I tried the latest release, now can't start the server.  Receiving this error:

```
ERROR [2022-08-30 06:06:20,092] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! liquibase.exception.ValidationFailedException: Validation Failed:
!      1 change sets check sum
!           changelogs/db.changelog-1.0.xml::create-users::athou was: 8:a19e9e8007137d83c8a6b9ead5a2ecac but is now: 8:5c5bffe50ff6c232247b6339c54139e1
! 
! at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:307)
! at liquibase.Liquibase.lambda$update$1(Liquibase.java:231)
! at liquibase.Scope.lambda$child$0(Scope.java:180)
! at liquibase.Scope.child(Scope.java:189)
! at liquibase.Scope.child(Scope.java:179)
! at liquibase.Scope.child(Scope.java:158)
! at liquibase.Liquibase.runInScope(Liquibase.java:2405)
! at liquibase.Liquibase.update(Liquibase.java:211)
! at liquibase.Liquibase.update(Liquibase.java:197)
! at liquibase.Liquibase.update(Liquibase.java:193)
! at liquibase.Liquibase.update(Liquibase.java:185)
! at com.commafeed.backend.service.StartupService.lambda$updateSchema$1(StartupService.java:63)
! ... 21 common frames omitted
```

database config in config.yml:

```
database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost/commafeed?autoReconnect=true&failOverReadOnly=false&maxReconnects=20&rewriteBatchedStatements=true
  user: [redacted]
  password: [redacted]
  properties:
    charSet: UTF-8

  validationQuery: "/* CommaFeed Health Check */ SELECT 1"
  minSize: 1
  maxSize: 50
  maxConnectionAge: 30m
```

**Comment by Athou** [comment]
What version were you updating from?

**Comment by chkrefr** [comment]
Ah of course, sorry, upgrading from version 2.5.0 (7b686d8).

**Comment by chkrefr** [comment]
Sure, very rusty in MySQL though so might take me some time to get around to getting it done properly.  If any readers can drop in the command I'd need then I'll gladly throw some praise your way lol.

**Comment by Athou** [comment]
Try something like this:

`UPDATE DATABASECHANGELOG SET MD5SUM=NULL WHERE ID='create-users';`

**Comment by chkrefr** [comment]
Yeap that exact command did the trick, commafeed spun up without issue after and is humming along nicely.  Thanks for the help, and if anyone else stumbles on this from the same error give the above a try on your database.
