### ISSUE TITLE
Can't start server; ArrayIndexOutOfBounds on StartupService

### ISSUE THREAD

**Issue by InvisibleUp** [Athou/commafeed#948]
Hello. I'm trying to set up commafeed on my server (using MySQL as the database) but I can't seem to get past this point in the startup. Here's a crash log:

```
INFO  [2020-11-27 06:33:32,102] liquibase.executor.jvm.JdbcExecutor: SELECT COUNT(*) FROM commafeed.DATABASECHANGELOGLOCK
INFO  [2020-11-27 06:33:32,115] liquibase.executor.jvm.JdbcExecutor: SELECT COUNT(*) FROM commafeed.DATABASECHANGELOGLOCK
INFO  [2020-11-27 06:33:32,119] liquibase.executor.jvm.JdbcExecutor: SELECT `LOCKED` FROM commafeed.DATABASECHANGELOGLOCK WHERE ID=1
INFO  [2020-11-27 06:33:32,177] liquibase.lockservice.StandardLockService: Successfully acquired change log lock
INFO  [2020-11-27 06:33:34,922] liquibase.executor.jvm.JdbcExecutor: SELECT MD5SUM FROM commafeed.DATABASECHANGELOG WHERE MD5SUM IS NOT NULL LIMIT 1
INFO  [2020-11-27 06:33:34,942] liquibase.executor.jvm.JdbcExecutor: SELECT COUNT(*) FROM commafeed.DATABASECHANGELOG
INFO  [2020-11-27 06:33:34,950] liquibase.changelog.StandardChangeLogHistoryService: Reading from commafeed.DATABASECHANGELOG
INFO  [2020-11-27 06:33:34,951] liquibase.executor.jvm.JdbcExecutor: SELECT * FROM commafeed.DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
INFO  [2020-11-27 06:33:35,117] liquibase.lockservice.StandardLockService: Successfully released change log lock
ERROR [2020-11-27 06:33:35,139] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.lang.ArrayIndexOutOfBoundsException: 1
! at liquibase.datatype.DataTypeFactory.fromDescription(DataTypeFactory.java:251)
! at liquibase.change.core.CreateTableChange.generateStatements(CreateTableChange.java:70)
! at liquibase.change.AbstractChange.generateStatementsVolatile(AbstractChange.java:287)
! at liquibase.change.AbstractChange.warn(AbstractChange.java:358)
! at liquibase.changelog.visitor.ValidatingVisitor.visit(ValidatingVisitor.java:109)
! at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
! at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:269)
! at liquibase.Liquibase.update(Liquibase.java:198)
! at liquibase.Liquibase.update(Liquibase.java:179)
! at liquibase.Liquibase.update(Liquibase.java:175)
! at liquibase.Liquibase.update(Liquibase.java:168)
! at com.commafeed.backend.service.StartupService.lambda$updateSchema$2(StartupService.java:67)
! ... 22 common frames omitted
! Causing: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 1
! at com.commafeed.backend.service.StartupService.lambda$updateSchema$2(StartupService.java:69)
! at org.hibernate.jdbc.WorkExecutor.executeWork(WorkExecutor.java:37)
! at org.hibernate.internal.SessionImpl$1.accept(SessionImpl.java:2361)
! at org.hibernate.internal.SessionImpl$1.accept(SessionImpl.java:2358)
! at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:320)
! at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2380)
! at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2365)
! at com.commafeed.backend.service.StartupService.updateSchema(StartupService.java:50)
! at com.commafeed.backend.service.StartupService.start(StartupService.java:41)
! at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
! at org.eclipse.jetty.server.Server.start(Server.java:418)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
! at org.eclipse.jetty.server.Server.doStart(Server.java:382)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:93)
! at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:171)
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 1
        at com.commafeed.backend.service.StartupService.lambda$updateSchema$2(StartupService.java:69)
        at org.hibernate.jdbc.WorkExecutor.executeWork(WorkExecutor.java:37)
        at org.hibernate.internal.SessionImpl$1.accept(SessionImpl.java:2361)
        at org.hibernate.internal.SessionImpl$1.accept(SessionImpl.java:2358)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.coordinateWork(JdbcCoordinatorImpl.java:320)
        at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2380)
        at org.hibernate.internal.SessionImpl.doWork(SessionImpl.java:2365)
        at com.commafeed.backend.service.StartupService.updateSchema(StartupService.java:50)
        at com.commafeed.backend.service.StartupService.start(StartupService.java:41)
        at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
        at org.eclipse.jetty.server.Server.start(Server.java:418)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:382)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at com.commafeed.CommaFeedApplication.main(CommaFeedApplication.java:171)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at liquibase.datatype.DataTypeFactory.fromDescription(DataTypeFactory.java:251)
        at liquibase.change.core.CreateTableChange.generateStatements(CreateTableChange.java:70)
        at liquibase.change.AbstractChange.generateStatementsVolatile(AbstractChange.java:287)
        at liquibase.change.AbstractChange.warn(AbstractChange.java:358)
        at liquibase.changelog.visitor.ValidatingVisitor.visit(ValidatingVisitor.java:109)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:269)
        at liquibase.Liquibase.update(Liquibase.java:198)
        at liquibase.Liquibase.update(Liquibase.java:179)
        at liquibase.Liquibase.update(Liquibase.java:175)
        at liquibase.Liquibase.update(Liquibase.java:168)
        at com.commafeed.backend.service.StartupService.lambda$updateSchema$2(StartupService.java:67)
        ... 22 more
```

I'm running OpenJDK 1.8.0_262 on CentOS 7. The database is `mysql  Ver 15.1 Distrib 5.5.65-MariaDB, for Linux (x86_64) using readline 5.1`.

**Comment by Athou** [comment]
I don't have a mariadb database to test, could you try to change migrations.xml inside commafeed.jar so that it reads `<property name="blob_type" value="blob" dbms="mysql,mariadb" />` instead of `<property name="blob_type" value="blob" dbms="mysql" />` and try again ?
